name: firebase_admin_interop
description: Firebase Admin SDK for Dart written as a wrapper around official Node.js SDK.
version: 1.2.2
homepage: https://github.com/pulyaevskiy/firebase-admin-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  js: ^0.6.1+1
  node_interop: ^1.0.0-dev.13.0
  meta: ^1.1.7
  quiver_hashcode: ^2.0.0

dev_dependencies:
  test: ^1.5.3
  build_runner: ^1.2.3
  build_node_compilers: ^0.2.1
  build_test:
